spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service_customer
          uri: lb://CONSUMER
          order: 0
          predicates:
            - Path=/customer/*
          filters:
            ## 截取路径位数
            - StripPrefix=1
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback



#            #限流
#            - name: RequestRateLimiter
#              args:
#                key-resolver: "#{@remoteAddrKeyResolver}"
#                ### 希望允许用户每秒处理多少个请求
#                redis-rate-limiter.replenishRate: 1
#                ### 用户允许在一秒钟内完成的最大请求数
#                redis-rate-limiter.burstCapacity: 2
      default-filters:
        - Elapsed=true
#        - name: Retry
#          args:
#            retries: 3
#            statuses: BAD_GATEWAY,BAD_REQUEST
#            methods: GET,POST


#      httpclient:
#        pool:
#          acquire-timeout: 10000
  redis:
    host: localhost
    port: 6379

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000

server:
  port: 10000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
