spring:
#  boot:
#    admin:
#      client:
#        url: http://localhost:18080

  sleuth:
    web:
      client:
        enabled: true
    sampler: 1.0
  zipkin:
    base-url: http://localhost:9411/
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/

feign:
  hystrix:
    enabled: true
ribbon:
  eureka:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO